### ISSUE TITLE
NIN_CMS_UTILS: eksporter cms objekter til csv-fil

### ISSUE THREAD

**Issue by stigat** [Artsdatabanken/nin-kode-api#15]
Objekttyper: Resource, Property, Content
Filer:
{NIN-version}_Resource.csv
{NIN-version}_Property.csv
{NIN-version}_Content.csv
{NIN-version}_Images.csv

**Comment by stigat** [comment]
Eksempel på format etter innhending av csv til (2 pages/resources, NiN2.0/L1-C-5 og NiN2.0/L1-C-6 )
[uttrekk_fra_ny_eksport.xlsx](https://github.com/Artsdatabanken/nin-kode-api/files/10020710/uttrekk_fra_ny_eksport.xlsx)

**Comment by stigat** [comment]
![image](https://user-images.githubusercontent.com/5111069/202157314-a95e1b25-bcc2-43a1-be55-4161da872031.png)

**Comment by stigat** [comment]
[forste_fulle_kjoring.zip](https://github.com/Artsdatabanken/nin-kode-api/files/10022008/forste_fulle_kjoring.zip)

**Comment by stigat** [comment]
[uttrekk_fra_ny_eksport.xlsx](https://github.com/Artsdatabanken/nin-kode-api/files/10131035/uttrekk_fra_ny_eksport.xlsx)

**Comment by runningbones** [comment]
https://www.artsdatabanken.no/NiN2.0/L1-C-5 (flere bilder ligger knytta til ressurs)

**Comment by stigat** [comment]
done dec 2022
